version : '3.0'

services:
    sshd:
        build: .
        ports:
            - "2222:22"
        volumes:
            - server_keys:/server_keys
        environment:
            - SSH_PUBKEY_1: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCWwATdfklgjhsdflkjghsdfkljghsdflkjgh...F6igWaN1zw== user@example
    
volumes:
    server_keys:
